#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."

REPO_ROOT=$(pwd)
ENV_FILE="$REPO_ROOT/.env"

# ─── Helpers ─────────────────────────────────────────────────────
function ask() {
  local prompt="$1"
  local default="$2"
  if [ -n "$default" ]; then
    read -rp "$prompt [$default]: " val
    echo "${val:-$default}"
  else
    read -rp "$prompt: " val
    echo "$val"
  fi
}

function ask_yesno() {
  local prompt="$1"
  local default="$2"
  while true; do
    read -rp "$prompt [y/N]: " yn
    yn=${yn:-$default}
    case "$yn" in
      [Yy]*) return 0 ;;
      [Nn]*) return 1 ;;
    esac
  done
}

function generate_secret() {
  openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1
}

# ─── Check prerequisites ─────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "❌ Docker is not installed. Install it first: https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
  echo "❌ Docker Compose is not installed. Install it first: https://docs.docker.com/compose/install/"
  exit 1
fi

# ─── Load existing values if any ─────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  echo "📄 Found existing .env file."
  if ! ask_yesno "Overwrite it with new values?" "N"; then
    echo "Keeping existing .env. Running deployment with current settings..."
    docker compose up --build -d
    echo ""
    echo "✅ Labify is deployed!"
    echo "   Frontend: http://$(grep '^HOST=' "$ENV_FILE" | cut -d= -f2):$(grep '^PORT=' "$ENV_FILE" | cut -d= -f2)"
    echo "   API:      http://$(grep '^HOST=' "$ENV_FILE" | cut -d= -f2):$(grep '^API_PORT=' "$ENV_FILE" | cut -d= -f2)"
    exit 0
  fi
fi

# ─── Interactive configuration ──────────────────────────────────
echo ""
echo "🧪 Labify Deployment Configuration"
echo "=================================="
echo ""
echo "This script will build Docker images and start Labify on your server."
echo "Clients will connect remotely via the domain or IP you provide."
echo ""

# Domain / IP
DOMAIN=$(ask "Public domain or IP (e.g. labify.domain.com or 192.168.1.10)")
if [ -z "$DOMAIN" ]; then
  echo "❌ Domain/IP is required."
  exit 1
fi

# Determine if domain looks like an IP
if [[ "$DOMAIN" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  APP_URL="http://$DOMAIN"
  CORS_ORIGIN="http://$DOMAIN"
else
  APP_URL="https://$DOMAIN"
  CORS_ORIGIN="https://$DOMAIN"
fi

# Ports
PORT=$(ask "Frontend port to expose on the host" "8080")
API_PORT=$(ask "API port to expose on the host (set to empty to hide API behind nginx proxy only)" "3000")
LISTEN=$(ask "Bind IP (0.0.0.0 for all interfaces, 127.0.0.1 for localhost only)" "0.0.0.0")

# JWT Secret
JWT_SECRET=$(ask "JWT secret (leave empty to auto-generate)")
if [ -z "$JWT_SECRET" ]; then
  JWT_SECRET=$(generate_secret)
  echo "   🔑 Generated JWT secret: ${JWT_SECRET:0:16}..."
fi

# Email (optional)
echo ""
echo "📧 Email configuration (optional — used for password reset & notifications)"
echo "   Leave all fields empty to skip email setup."
EMAIL_SERVICE=$(ask "Email service (gmail, outlook365, sendgrid, or leave empty for custom SMTP)" "")
SMTP_HOST=""
SMTP_PORT="587"
SMTP_USER=""
SMTP_PASS=""
FROM_EMAIL=""

if [ -n "$EMAIL_SERVICE" ]; then
  SMTP_USER=$(ask "SMTP username / email address")
  SMTP_PASS=$(ask "SMTP password or app-specific password")
  FROM_EMAIL=$(ask "From email address" "$SMTP_USER")
else
  SMTP_HOST=$(ask "Custom SMTP host (e.g. smtp.gmail.com, leave empty to skip)" "")
  if [ -n "$SMTP_HOST" ]; then
    SMTP_PORT=$(ask "SMTP port" "587")
    SMTP_USER=$(ask "SMTP username")
    SMTP_PASS=$(ask "SMTP password")
    FROM_EMAIL=$(ask "From email address" "$SMTP_USER")
  fi
fi

# ─── Write .env ──────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# ─── Generated by scripts/deploy.sh ─────────────────────────────

# Frontend / public access
DOMAIN=$DOMAIN
APP_URL=$APP_URL
CORS_ORIGIN=$CORS_ORIGIN

# Bind configuration
LISTEN=$LISTEN
HOST=$LISTEN
PORT=$PORT
API_PORT=$API_PORT

# API settings
API_PORT_CONTAINER=3000
DATABASE_PATH=/data/labify.db
JWT_SECRET=$JWT_SECRET

# Email
EMAIL_SERVICE=$EMAIL_SERVICE
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS
FROM_EMAIL=$FROM_EMAIL
EOF

echo ""
echo "✅ Configuration saved to .env"
cat "$ENV_FILE"
echo ""

# ─── Build & start ───────────────────────────────────────────────
echo "🔨 Building Docker images (no cache) and starting containers..."
docker compose up --build -d

echo ""
echo "🚀 Labify deployed successfully!"
echo ""
echo "   Frontend: $APP_URL (or http://$LISTEN:$PORT)"
if [ -n "$API_PORT" ]; then
  echo "   API direct: http://$LISTEN:$API_PORT"
fi
echo ""
echo "   API is also proxied through nginx at /api/ on the frontend URL."
echo ""

# ─── Health check ────────────────────────────────────────────────
echo "⏳ Waiting for services to start..."
sleep 3

if curl -sf "http://$LISTEN:$PORT" > /dev/null 2>&1; then
  echo "   ✅ Frontend responding at http://$LISTEN:$PORT"
else
  echo "   ⚠️  Frontend not responding yet (may need a few more seconds)"
fi

if curl -sf "http://$LISTEN:$API_PORT/api/health" > /dev/null 2>&1; then
  echo "   ✅ API responding at http://$LISTEN:$API_PORT/api/health"
else
  echo "   ⚠️  API not responding yet (may need a few more seconds)"
fi

echo ""
echo "To update and redeploy later, run:"
echo "   docker compose up --build -d"
echo ""
